accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import SignupView, LoginView
from . import views
app_name='accounts'

urlpatterns = [
    path('', views.index_view, name='accounts_index'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<str:uid>/', views.profile_view, name='profile'),
    path('profile/<str:uid>/edit', views.profile_edit, name='accounts_edit'),
    path('users/', views.users_view, name='users'),
    path('delete/', views.delete_view, name='delete'),            
]

bloggy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf import settings
from post import views as postViews

urlpatterns = [
    path('', postViews.index, name='home'),
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('api/', include('likesdislikes.urls', namespace='likesdislikes')),
    path('api/', include('bookmarks.urls', namespace='bookmarks')),    
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='post'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('edit/<slug>/', views.pre_edit, name='pedit'),
    path('<slug:slug>/edit/', views.edit_view, name='edit'),
    path('<slug:slug>/delete/', views.post_delete, name='post_delete'),    
    path('<slug:slug>/', views.detail, name='detail'),
    # path('<slug:slug>/plz/', views.edit, name='edit'),
    path('api/search/', views.serach_View, name='search')         
]

accounts/models.py
# Create your models here


from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# from django.shortcuts import get
from post.utils import rand_uid
# from likesdislikes import models as likemodels
# from post.models import Post

class UserProfileManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, bio=None, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        if not first_name:
            raise ValueError("Users must have first name")
        if not last_name:
            raise ValueError("Users must have a last name")
        user = self.model(
            email = self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            bio=bio
        )
        user.set_password(password)
        # user.staff = is_staff
        # user.admin = is_admin
        # user.active = is_active
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, first_name, last_name , bio=None, password=None):
        user = self.create_user(
            email,
            first_name, 
            last_name,
            bio=bio,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, bio=None, password=None):
        user = self.create_user(
            email, 
            first_name, 
            last_name,
            bio=bio,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class UserProfile(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255, blank=True, null=True) 
    bio = models.CharField(max_length=255, blank=True, null=True)   
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    uid = models.CharField(max_length=8, unique=True)
    # profile_pic = models.ImageField(default='guest-user.png', upload_to='ProfilePic', blank=True)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserProfileManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.first_name + self.last_name

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True


    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

    # @property
    # def liked(self):
    #     return likemodels.LikeDislike.objects.filter_by_instance(self)


    
def get_uid(instance, uid=None):
    _uid = rand_uid()
    if uid is not None:
        _uid = uid
    qs = UserProfile.objects.filter(uid=_uid)
    exists = qs.exists()
    if exists:
        _uid = rand_uid()
    return _uid

def user_pre_save(signal, instance, sender, **kwargs):
    if not instance.uid:
        instance.uid = get_uid(instance)

# Signals
pre_save.connect(user_pre_save, sender=UserProfile)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import UserProfile
from django.contrib.auth.forms import UserChangeForm

class UserProfileAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name','email', )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserProfileAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserProfileAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name','email', 'password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class SignupForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta():
        model = UserProfile
        fields = ('first_name', 'last_name','email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        # user.active = False
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    # first_name = forms.CharField(label="First Name")
    # last_name = forms.CharField(label="Last Name")
    password = forms.CharField(widget=forms.PasswordInput)


class ProfileEditForm(forms.ModelForm):
    # email = forms.EmailField(required=True)
    # first_name = forms.CharField(max_length=255 ,required=False)
    # last_name = forms.CharField(max_length=255 ,required=False)
    # bio = forms.CharField(max_length=255 ,required=False)

    class Meta:
        model = UserProfile
        fields = ('email', 'first_name', 'last_name', 'bio')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import SignupForm, LoginForm, ProfileEditForm
from django.views.generic import CreateView, FormView
from django.contrib.auth.decorators import login_required
from .models import UserProfile
from post import models
from bookmarks.models import BookmarkPost
from likesdislikes.models import LikeDislike
# Create your views here.

# def signup_view(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             if 'next' in request.POST:
#                 return redirect(request.POST.get.next)
#             else:
#                 return redirect('post:index')
#     else:
#         form = SignupForm()
#     return render(request, 'accounts/signup.html',{'form':form})

# def login_view(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
#             return redirect('post:index')
#     else:
#         form = AuthenticationForm()
#     return render(request, 'accounts/login.html', {'form':form})

def index_view(request):
    context = {}
    return render(request, 'accounts/accounts_index.html', context)


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('post:index')    

@login_required(login_url="/accounts/login/")
def profile_view(request, uid):
    user = get_object_or_404(UserProfile, uid=uid)
    user_posts = models.Post.objects.filter(author=user).order_by('-pub_date')
    user_bookmarks = BookmarkPost.objects.filter(user=user)
    user_liked = LikeDislike.objects.likes().filter(user=user)
    user_liked_posts = user_liked.filter(content_type=ContentType.objects.get_for_model(models.Post))
        
    tab = request.GET.get('tab')
    
    context = {
        'user':user, 
        'user_posts':user_posts, 
        'user_bookmarks' : user_bookmarks, 
        'user_liked_posts': user_liked_posts,
        'tab':tab
    }
    return render(request, 'accounts/profile.html', context)

class SignupView(CreateView):
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = '/'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        else:
            form = self.form_class() 
            return render(request, self.template_name, {'form': form})

class LoginView(FormView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    success_url = '/'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('/')
        else:
            form = self.form_class() 
            return render(request, self.template_name, {'form': form})

    
    def form_valid(self, form):
        request = self.request
        email = form.cleaned_data["email"]
        # first_name = form.cleaned_data("first_name")
        # last_name = form.cleaned_data("last_name")
        password = form.cleaned_data["password"]
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('post:index')
        return super(LoginView, self).form_invalid(form)
            
@login_required(login_url="/accounts/login/")
def profile_edit(request, uid):
    user = get_object_or_404(UserProfile, uid=uid)
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=user)
        print(form.errors)
        if form.is_valid():
            user.bio = request.POST['bio']
            print(form.errors)
            form.save()
            return redirect('accounts:profile', uid=user.uid)
    else:
        form = ProfileEditForm(instance=user)
    return render(request, 'accounts/profile_edit.html', {'user':user, 'form':form})


def users_view(request):
    user = request.user
    users = UserProfile.objects.all().exclude(email=user.email)
    context = {
        'user':user,
        'users':users
    }
    return render(request, 'accounts/all_users.html', context)

@login_required(login_url="/accounts/login/")
def delete_view(request):
    user = request.user
    
    if request.method == 'POST':
        user.delete()
        messages.add_message(request, messages.SUCCESS, 'Account Deleted')
        return redirect('accounts:signup')
    context = {}
    return render(request, 'accounts/delete.html', context)

accounts/templates/accounts/accounts_index.html
{% extends "layout.html" %}


{% block title %}Accounts | Bloggy{% endblock title %}
    
{% block content %}
    <div class="container">
        <p class="breadcrumbs" id="bc">
            <span class="post-labels">
                <a href="{% url 'home' %}" rel="tag" title="Home">Home</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'accounts:accounts_index' %}" rel="tag" title="Accounts">Accounts</a>
            </span>
        </p>
        <section>
            <div class="cards">
                <div class="row">
                    <div class="col m12 s12">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title"><a href="{% url 'accounts:profile' uid=user.uid %}">Your Account</a></span>
                                <p>I am a very simple card. I am good at containing small bits of information.
                                I am convenient because I require little markup to use effectively.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col m12 s12">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title"><a href="{% url 'accounts:accounts_edit' uid=user.uid %}">Edit</a></span>
                                <p>I am a very simple card. I am good at containing small bits of information.
                                I am convenient because I require little markup to use effectively.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col m12 s12">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title"><a href="{% url 'accounts:users' %}">All User</a></span>
                                <p>I am a very simple card. I am good at containing small bits of information.
                                I am convenient because I require little markup to use effectively.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col m12 s12">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title"><a href="{% url 'home' %}">Delete</a></span>
                                <p>I am a very simple card. I am good at containing small bits of information.
                                I am convenient because I require little markup to use effectively.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}
    

accounts/templates/accounts/all_users.html
{% extends "layout.html" %}

{% block title %}All Users | Bloggy{% endblock%}
{% block content %}
    <div class="container">
        <p class="breadcrumbs" id="bc">
            <span class="post-labels">
                <a href="{% url 'home' %}" rel="tag" title=" ">Home</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'accounts:accounts_index' %}" rel="tag" title=" ">Accounts</a>
                <i class="fa fa-angle-right"></i>
                <span>All Users</span>
            </span>
        </p>
        <div class="main" style="margin-top:5rem;">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{user.first_name}}</span>
                    <p>{{user.email}}</p>
                    {% if user.bio %}
                        <p>{{user.bio}}</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <section id="users">
            
            {% for u in users %}
                <div class="card">
                    <div class="card-content">
                        <a class="card-title" href="{% url 'accounts:profile' uid=u.uid %}">{{u.first_name}}</a>
                        <p>{{u.email}}</p>
                        {% if u.bio %}
                            <p>{{u.bio}}</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
                
        </section>

    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "layout.html" %}
{% block style %}
    <style>
        #profileImg {
            max-width: 100%;
        }
    </style>
{% endblock style %}
{% block title %}Profile | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
            <p class="breadcrumbs" id="bc">
                <span class="post-labels">
                    <a href="{% url 'home' %}" rel="tag" title=" ">Home</a>
                    <i class="fa fa-angle-right"></i>
                    <a href="{% url 'accounts:accounts_index' %}" rel="tag" title=" ">Accounts</a>
                    <i class="fa fa-angle-right"></i>
                    <span>{{user.first_name}}</span>
                </span>
            </p>
        <div class="main" style="margin-top:5rem;">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{user.first_name}}</span>
                    <p>{{user.email}}</p>
                    {% if user.bio %}
                        <p>{{user.bio}}</p>
                    {% endif %}
                    <p>Joined at: {{user.timestamp | date}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <ul class="tabs grey-text">
                        <li class="tab col s3 grey-text"><a {% if tab == 'post' %} class="active grey-text"{% endif %} class="grey-text" href="#posts">Post</a></li>
                        <li class="tab col s3 grey-text"><a {% if tab == 'bookmarks' %} class="active grey-text"{% endif %} class="grey-text" href="#bookmarks">Bookmarks</a></li>
                        <li class="tab col s3 grey-text"><a {% if tab == 'liked' %} class="active grey-text"{% endif %} class="grey-text" href="#liked">Liked</a></li>                        
                    </ul>
                </div>
            </div>
            
            <section id="posts">
                <!-- <h4>Recent posts</h4> -->
                <ul class="collection with-header">
                    <li class="collection-header"><h4>Recent posts</h4></li>
                    
                    {% for post in user_posts %}
                        <li class="collection-item">
                            <div>
                                {{post.title}}
                                
                                {% if request.user == post.author %}
                                    <a href="{% url 'post:pedit' slug=post.slug %}" class="secondary-content">
                                        <i class="material-icons black-text">edit</i>
                                    </a>
                                {% endif %}
                                    <a href="{% url 'post:detail' slug=post.slug %}" class="secondary-content">
                                        <i class="material-icons black-text">remove_red_eye</i>
                                    </a>
                            </div>
                        </li>
                    {% endfor %} 
                </ul>
            </section>
            <section id="bookmarks">
                <ul class="collection with-header">
                    <li class="collection-header"><h4>Recent Bookmarks</h4></li>
                    
                    {% if user_bookmarks %}
                        {% for b in user_bookmarks %}
                            <li class="collection-item">
                                <div>
                                    {{b.obj.title}}

                                    {% if request.user == b.obj.author %}
                                        <a href="{% url 'post:pedit' slug=b.obj.slug %}" class="secondary-content">
                                            <i class="material-icons black-text">edit</i>
                                        </a>
                                    {% endif %}

                                    <a href="{% url 'post:detail' slug=b.obj.slug %}" class="secondary-content">
                                        <i class="material-icons black-text">remove_red_eye</i>
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                            <li class="collection-item">No Bookmarks</li>
                    {% endif %}
                        
                        
                </ul>
                    
            </section>
            <section id="liked">
                <ul class="collection with-header">
                    <li class="collection-header"><h4>Liked Posts</h4></li>
                    
                    {% if user_liked_posts %}
                        {% for l in user_liked_posts %}
                            <li class="collection-item">
                                <div>
                                    
                                    {{l.content_object.title}}

                                    {% if request.user == l.content_object.author %}
                                        <a href="{% url 'post:pedit' slug=l.content_object.slug %}" class="secondary-content">
                                            <i class="material-icons black-text">edit</i>
                                        </a>
                                    {% endif %}

                                    <a href="{% url 'post:detail' slug=l.content_object.slug %}" class="secondary-content">
                                        <i class="material-icons black-text">remove_red_eye</i>
                                    </a>
                                        
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="collection-item">No Liked Posts</li>
                    {% endif %}
                </ul>
            </section>
        {% comment %} <p></p> {% endcomment %}
        </div>
    </div>
{% endblock content %}
{% block script %}
    
    {% comment %}
        
    
        
    {% if tab == 'posts' %}
        <script>
            $('ul.tabs').tabs('select_tab', '#posts');
        </script>
    {% endif %}
    {% if tab == 'bookmarks' %}
        <script>
            $('ul.tabs').tabs('select_tab', '#bookmarks');
        </script>
    {% endif %}
    {% endcomment %}    
    <script>
        
    </script>
{% endblock script %}

accounts/templates/accounts/profile_edit.html
{% extends "layout.html" %}

{% block title %}Edit Profile | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
        <p class="breadcrumbs" id="bc">
            <span class="post-labels">
                <a href="{% url 'home' %}" rel="tag" title="Home">Home</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'accounts:accounts_index' %}" rel="tag" title="Accounts">Accounts</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'accounts:accounts_index' %}" rel="tag" title="Accounts">{{user.first_name}}</a>
                <i class="fa fa-angle-right"></i>
                <span>Edit</span>
            </span>
        </p>
        <div class="row">
            <form action="{% url 'accounts:accounts_edit' uid=user.uid %}" method="POST" class="site-form col s12 m8 offset-m2 z-depth-5 grey white-text" style="padding-bottom:3rem;padding-top: 1rem;padding-left: 4rem;padding-right: 4rem;margin-top:2rem;color:white;">
                <h3>Edit</h3>
                {% csrf_token %}
                <div class="input-field" style="margin-bottom:2rem;">
                    {{form.first_name}}
                    {{form.first_name.label_tag}}
                </div>
                <div class="input-field" style="margin-bottom:2rem;">
                    {{form.last_name}}
                    {{form.last_name.label_tag}}
                </div>
                <div class="input-field">
                    {{form.email}}
                    {{form.email.label_tag}}
                </div>
                <br>
                <div class="input-field" style="margin-bottom:2rem;">
                    {{form.bio}}
                    {{form.bio.label_tag}}
                </div>
                
                <!-- {{form.as_p}} -->
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}">
                {% endif %}
                <input type="submit" value="Save" class="btn white black-text">
            </form>
        </div>
    </div>
{% endblock content %}


{% block script %}
    <script>
        $('#id_email').attr('data-length', '30');
        $('#id_first_name').attr('data-length', '15');
        $('#id_last_name').attr('data-length', '15');        
        $('#id_bio').attr('data-length', '100')
        
        $('input#id_first_name, input#id_last_name, input#id_email, input#id_bio').characterCounter();
    </script>
{% endblock script %}
    

accounts/templates/accounts/signup.html
{% extends "layout.html" %}

{% block title %}Signup | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
        <p class="breadcrumbs" id="bc">
            <span class="post-labels">
                <a href="{% url 'home' %}" rel="tag" title="Home">Home</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'accounts:accounts_index' %}" rel="tag" title="Accounts">Accounts</a>
                <i class="fa fa-angle-right"></i>
                <span>Signup</span>
            </span>
        </p>
        {% comment %} <form action="{% url 'accounts:signup' %}" method="POST" class="site-form">
            {% csrf_token %} 
            {{form}}
            <input type="submit" value="Signup" class="btn grey white-text">
        </form> {% endcomment %}
        <div class="row">
                <form action="{% url 'accounts:signup' %}" method="POST" class="site-form col s12 m8 offset-m2 z-depth-5 grey white-text" style="padding-bottom:3rem;padding-top: 1rem;padding-left: 4rem;padding-right: 4rem;margin-top:4rem;color:white;">
                    <h3>Signup</h3>
                    {% csrf_token %}
                    <div class="input-field" style="margin-bottom:2rem;">
                        {{form.first_name}}
                        {{form.first_name.label_tag}}
                    </div>
                    <div class="input-field" style="margin-bottom:2rem;">
                        {{form.last_name}}
                        {{form.last_name.label_tag}}
                    </div>
                    <div class="input-field">
                        {{form.email}}
                        {{form.email.label_tag}}
                    </div>
                    <br>
                    <div class="input-field">
                        {{form.password1}}
                        {{form.password1.label_tag}}
                    </div>
                    <div class="input-field" style="margin-bottom:2rem;">
                        {{form.password2}}
                        {{form.password2.label_tag}}
                    </div>
                    
                    <!-- {{form.as_p}} -->
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{request.GET.next}}">
                    {% endif %}
                    <input type="submit" value="Signup" class="btn white black-text">
                </form>
            </div>
    </div>

{% endblock content %}

{% block script %}
    <script>
        $('#id_email').attr('data-length', '15');
        $('#id_first_name').attr('data-length', '15');
        $('#id_last_name').attr('data-length', '15');        
        $('#id_password1').attr('data-length', '20');
        $('#id_password2').attr('data-length', '20');
        
        $('input#id_username, textarea#id_password1, input#id_password2').characterCounter();
        
    </script>
{% endblock script %}