accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import SignupView, LoginView
from . import views
app_name='accounts'

urlpatterns = [
    path('', views.index_view, name='accounts_index'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<str:uid>/', views.profile_view, name='profile'),
    path('profile/<str:uid>/edit', views.profile_edit, name='accounts_edit'),
    path('users/', views.users_view, name='users'),
    path('delete/', views.delete_view, name='delete'),            
]

bloggy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from django.conf.urls.static import static
from django.conf import settings
from post import views as postViews

urlpatterns = [
    path('', postViews.index, name='home'),
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('api/', include('likesdislikes.urls', namespace='likesdislikes')),
    path('api/', include('bookmarks.urls', namespace='bookmarks')),    
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='comments'

urlpatterns = [
    path('<int:pk>', views.comment_thread, name='thread'),
    path('<int:pk>/delete/', views.comment_delete, name='comment_delete'),    
]

post/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='post'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('edit/<slug>/', views.pre_edit, name='pedit'),
    path('<slug:slug>/edit/', views.edit_view, name='edit'),
    path('<slug:slug>/delete/', views.post_delete, name='post_delete'),    
    path('<slug:slug>/', views.detail, name='detail'),
    # path('<slug:slug>/plz/', views.edit, name='edit'),
    path('api/search/', views.serach_View, name='search')         
]

post/models.py
from django.db import models
import datetime
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_save
from accounts.models import UserProfile
from comments.models import Comment
from .utils import rand_slug
from pagedown.widgets import PagedownWidget
from markdown_deux import markdown
from likesdislikes.models import LikeDislike
# Create your models here.

class PostManager(models.Manager):
    
    def get_bookmark_count(self):
        return self.bookmarkpost_set().all().count()

class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    slug = models.SlugField(max_length=8,unique=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    votes = GenericRelation(LikeDislike, related_query_name='posts')
    thumbnail = models.ImageField(default='default.jpg', blank=True)
    author = models.ForeignKey(UserProfile ,on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug': self.slug})

    def get_markdown(self):
        return mark_safe(markdown(self.body))

    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

    objects = PostManager()


def create_slug(post, new_slug=None):
    slug = rand_slug()
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = '{slug}{id}'.format(slug=slug, id=post.id)
        return create_slug(post, new_slug=new_slug)
    return slug

def post_pre_save(signal, instance, sender, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


# class LikePost(models.Model):
#     user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
#     post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
#     liked_at = models.DateTimeField(auto_now_add=True)



##### signals ######
# Execute signals pre_save
pre_save.connect(post_pre_save, sender=Post)

post/forms.py
from django import forms
from . import models
from pagedown.widgets import PagedownWidget

class CreatePost(forms.ModelForm):
    body = forms.CharField(widget=PagedownWidget(show_preview=False))
    class Meta:
        model = models.Post
        
        fields = ['title', 'body', 'thumbnail']

class PostAdminChangeForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ('title', 'body', 'slug','thumbnail', 'author',)
        
class PostAdminCreationForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ('title', 'body', 'thumbnail','author')
        
        

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post
from comments.models import Comment
from likesdislikes.models import LikeDislike
from comments.forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from . import forms

import json
# Create your views here.

def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    q = request.GET.get('q')    
    if q:
        post_list = post_list.filter(
            Q(title__icontains=q)|
            Q(body__icontains=q)|
            Q(author__first_name__icontains=q)|
            Q(author__last_name__icontains=q)
        ).distinct()

    by = request.GET.get('by')
    if by:
        post_list = post_list.order_by(by)

    paginator = Paginator(post_list, 20) # Show 20 post per page

    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'title': 'Home | Bloggy',
        'posts': posts,
        'q':q,
        'by':by
    }
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    print("ip: {}".format(ip))
    return render(request, 'post/index.html', context)
    #return HttpResponse("Hello World")

@login_required(login_url="/accounts/login/")
def create(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.author = request.user
            f.save()
            messages.add_message(request,messages.INFO,  'Post Created')
            return redirect('post:index')
            
    else:
        form = forms.CreatePost()
    return render(request, 'post/create.html', {'form':form})

def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments #Comment.objects.filter_by_instance(post)
    initial_data = {
        'content_type':post.get_content_type,
        'object_id':post.id,
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated:
        print(comment_form.cleaned_data)
        c_type = comment_form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get('object_id')
        content = comment_form.cleaned_data.get('content')
        parent_comment_obj = None
        try:
            parent_comment_id = request.POST.get('parent_comment_id')
        except:
            parent_comment_id = None
        
        if parent_comment_id:
            parent_qs =Comment.objects.filter(id=parent_comment_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_comment_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id = obj_id,
            content=content,
            parent_comment=parent_comment_obj
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    # like_obj = LikeDislike
    context = {
        'post':post,
        'comments':comments,
        'comment_form':comment_form
    }
    return render(request, 'post/details.html', context)

@login_required(login_url="/accounts/login/")
def edit_view(request, slug):
    # post = get_object_or_404(Post, slug=slug)
    # form = forms.CreatePost(request.POST or None, instance=post)

    # if form.is_valid():
    #     f = form.save(commit=False)
    #     f.save()
    #     return redirect('post:detail', slug=slug)
    # else:
    # form = forms.CreatePost(instance=post)
    return render(request, 'post/details.html')#{'form':form})
    # return HttpResponse('helllo Bitcoonnnnecttttttt')

@login_required(login_url="/accounts/login/")
def delete(request, slug):
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    return redirect('post:list')

def edit_call(request, s):
    post = get_object_or_404(Post, slug=s)
    form = forms.CreatePost(instance=post)    
    return render(request, 'post/edit.html', {'form':form})

def pre_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = forms.CreatePost(request.POST or None, instance=post)
    return render(request, 'post/pre.html', {'form':form})

def post_delete(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        if request.user != post.author:
            res = HttpResponse('No!')
            res.status_code = 403
            return res
        else:
            post.delete()
            messages.add_message(request, messages.ERROR, 'Post Deleted')
            return redirect('home')
        
    return render(request, 'post/post_delete.html', {'post':post})


def serach_View(request):
    post_list = Post.objects.all().order_by('-pub_date')    
    q = request.GET.get('q')
    print(q)
    if q:
        post_list = post_list.filter(
            Q(title__icontains=q)|
            Q(body__icontains=q)|
            Q(author__first_name__icontains=q)|
            Q(author__last_name__icontains=q)
        ).distinct()
        result = True
    else:
        result = False

    # data = {

    # }

    data = serializers.serialize('json', post_list)
    return HttpResponse(data, content_type="application/json")

    # return HttpResponse(
    #     json.dumps({
    #         "result":result,
    #         "post_list":post_list
    #     }),
    #     content_type="application/json"
    # )

post/templates/post/create.html
{% extends "layout.html" %}

{% block head %}
    {{form.media}}
{% endblock head %}

{% block title %}Create post | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
        <p class="breadcrumbs" id="bc">
            <span class="post-labels">
                <a href="{% url 'home' %}" rel="tag" title="Home">Home</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'home' %}" rel="tag" title="Post">Post</a>
                <i class="fa fa-angle-right"></i>
                <span>Create</span>
            </span>
        </p>
        <div class="row">
            <ul id="tabs-swipe-demo" class="tabs grey" style="margin-top:6rem;">
                <li class="tab col s3"><a class="active white-text" href="#test-swipe-1">Title</a></li>
                <li class="tab col s3"><a class="white-text" href="#test-swipe-2">Body</a></li>
                <li class="tab col s3"><a class="white-text" href="#test-swipe-3">Thumbnail</a></li>
                <li class="tab col s3"><a class="white-text" href="#test-swipe-4">Preview</a></li>             
            </ul>
            <!-- <div id="test-swipe-1" class="col s12"> -->
                <form action="{% url 'post:create' %}" method="POST" enctype="multipart/form-data" class="create-form col s12 z-depth-1" style="padding-bottom:3rem;padding-top: 1rem;padding-left: 4rem;padding-right: 4rem;margin-top:4rem;">
                    <!-- <h3>Create</h3> -->
                    {% csrf_token %}
                    {% comment %} {{form.as_p}} {% endcomment %}
                    <div id="test-swipe-1">
                        <h3>Title</h3>
                        <div class="input-field">
                            {{form.title}}
                            <!-- {{form.title.label_tag}} -->
                        </div>
                    </div>
                    <div id="test-swipe-2">
                        <h3>Body</h3>
                        <div class="input-field">
                            {{form.body}}
                            <!-- {{form.body.label_tag}} -->
                        </div>
                    </div>
                    <div id="test-swipe-3">
                        <h3>Thumbnail</h3>
                        <div class="file-field input-field">
                            <div class="btn black">
                                <span>Thumbnail</span>
                                {{form.thumbnail}}
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="Upload one or more files">
                            </div>
                            <input type="submit" value="Create" class="btn black">
                        </div>
                    </div>
                    <br>
                    <div id="test-swipe-4" class="col s12 preview">
                        <p>Preview</p>
                        <h3 class="preview-title"></h3>
                        <p class="preview-content"></p>
                    </div>
                </form>
            <!-- </div> -->
        </div>
        
    </div>
{% endblock content %}

{% block script %}
    <script>
        $('#id_title').attr('placeholder', 'Title ..');
        $('#id_body').attr('placeholder', 'Body here..');
        $(document).ready(function(){
            $('ul.tabs').tabs();

            let _title = $('#id_title');
            _title.on('keyup', (e)=> {
                console.log(_title.val());
                $('.preview-title').text(_title.val());
            });

            let _body = $('#id_body');
            _body.on('change', (e) => {
                console.log('changed');
                $('.preview-content').html(marked(_body.val()));
            })
            
            
        });


    </script>
{% endblock script %}

post/templates/post/details.html
{% extends "layout.html" %}
{{form.media}}
{% block title %}{{post.title}} | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
        <p class="breadcrumbs" id="bc">
            <span class="post-labels">
                <a href="{% url 'home' %}" rel="tag" title="Home">Home</a>
                <i class="fa fa-angle-right"></i>
                <a href="{% url 'home' %}" rel="tag" title="Post">Post</a>
                <i class="fa fa-angle-right"></i>
                <span>{{post.title}}</span>
            </span>
        </p>
        <!-- <a href="{% url 'post:edit' slug=post.slug %}">efiy</a> -->
        <!-- <a href="{% url 'post:pedit' post.slug %}">efiy</a> -->
        
        <!-- {% if post.thumbnail %}
            <div>
                <img src="{{post.thumbnail.url}}" class="materialboxed responsive-img thumb-img" width="700" alt="thumbnail">
            </div>
        {% endif %} -->
        <!-- <hr> -->
        <div class="main-post" style="margin-top:4rem;">
            <div class="card">
                <div class="card-content">
                    <p class="">{{post.get_markdown | safe}}</p>
                </div>
                <div class="card-action row">
                    <ul class="col m6 s12">
                        <div class="row">
                            <li data-id="{{ post.id }}" data-type="post" data-action="like" title="Like" class="col m4">
                                <i class="material-icons" id="thumbUpBtn">thumb_up</i>
                                <span data-count="like">{{ post.votes.likes.count }}</span>
                            </li>
                            <li data-id="{{ post.id }}" data-type="post" data-action="dislike" title="Dislike" class="col m4">
                                <i class="material-icons" id="thumbDownBtn">thumb_down</i>
                                <span data-count="dislike">{{ post.votes.dislikes.count }}</span>
                            </li>
                            <li data-id="{{ post.id }}" data-type="post" data-action="bookmark" title="Favorites" class="col m4">
                                <i class="material-icons">favorite</i>
                                <span data-count="bookmark">{{ post.get_bookmark_count }}</span>
                            </li>
                        </div>
                    </ul>
                    <div class="info col m6 s12">
                        <span class="new badge black" data-badge-caption="">author:<a href="{% url 'accounts:profile' uid=post.author.uid %}" style="margin-right:0;">{{post.author.first_name}}</a></span>
                        <span class="new badge black" data-badge-caption="{{ post.pub_date|timesince }} ago."></span>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- <hr> -->
        <div class="card">
            <div class="comments" style="padding:3rem;">
                <div class="card-title">
                    <h5>Comments</h5>
                </div>
                
                
                {% if user.is_authenticated %}
                    <form method="POST" action="{% url 'post:detail' slug=post.slug %}" style="margin-bottom:5rem;">
                        {% csrf_token %}
                        {{comment_form.object_id}}
                        {{comment_form.content_type}}                
                        <div class="input-field">
                            {{comment_form.content}}
                            <!-- {{comment_form.content.label_tag}} -->
                        </div>
                        <input type="submit" value="Comment" class="btn black right">
                        <div class="clearfix"></div>
                    </form>
                {% else %}
                    <p>Login to comment on this.</p>
                {% endif %}

                {%for c in comments%}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{c.user.first_name}}</span>
                            <p>{{c.content}}</p>
                        </div>
                        <div class="card-action">
                            <a class="replyButton{{c.id}}" style="cursor:pointer">Reply</a>
                            
                            {% if c.children_comment %}
                                <a class="showReplyButton" style="cursor:pointer">view Replies
                                {% if c.children_comment.count > 0 %}
                                    ( {{c.children_comment.count}} )
                                {% endif %} </a>
                            {% endif %}
                                
                            
                            {% if request.user == c.user %}
                                <a class="" href="{% url 'comments:comment_delete' pk=c.id %}">Delete</a>                           
                            {% endif %}
                                
                            <a class='dropdown-button' data-activates='dropdown1'><i class="material-icons right">more_vert</i></a>
                            <span class="right">{{c.timestamp|timesince}} ago</span>
                        </div>
                        <div class="replies">
                            {% for c_c in c.children_comment %}
                            <ul class="collection with-header">
                                <!-- <li class="collection-header"><h4>First Names</h4></li> -->
                                <li class="collection-item"><div>{{c_c.content}} {% if request.user == c.user %}<a href="{% url 'comments:comment_delete' pk=c_c.id %}" class="secondary-content"><i class="material-icons">delete</i></a>{% endif %}</div></li>
                            </ul>
                            {% endfor %}
                        </div>
                        <div class="row replyForm" id="r{{c.id}}">
                            <form method="POST" action="{% url 'post:detail' slug=post.slug %}">
                                {% csrf_token %}
                                {{comment_form.object_id}}
                                {{comment_form.content_type}}                
                                <div class="input-field col m6 s8 offset-m1 offset-s2">
                                    {{comment_form.content}}
                                    <!-- {{comment_form.content.label_tag}} -->
                                </div>
                                <input type="hidden" name="parent_comment_id" value="{{c.id}}">
                                <input type="submit" value="Reply" class="btn black col m2 s2">
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                {%endfor%}
            </div>
        </div>
        <!-- <div class="fb-comments" data-href="{{request.get_absolute_uri}}" data-numposts="5"></div> -->
    </div>

    <!-- Dropdown Structure -->
    <ul id='dropdown1' class='dropdown-content'>
      <li><a href="#!">Delete</a></li>
      <li><a href="#!">Report</a></li>
    </ul>
    
{% endblock content %}

{% block script %}
    <script>
        $(document).ready(function(){
            $('.materialboxed').materialbox();
                /*<!-- let mc = $('.marked-content');
                let content = $(mc).text();
                let markedContent = marked(content);
                mc.html(markedContent);

                $('marked-content img').each(() => {
                    $(this).addClass('responsive-img');
                }); */
            $('.replyForm').hide();
            $('.replies').hide();
            $('.showReplyButton').click(e => {
                $('.replyForm').fadeOut();
                $('.replies').fadeToggle();
                e.preventDefault();
            })
            
        });
    </script>
    {% for c in comments %}
        <script>
            $('.replyButton{{c.id}}').click(e=>{
                $('.replies').fadeOut();
                /*$('.replyForm').fadeToggle();*/
                $('#r{{c.id}}').fadeToggle()
                e.preventDefault();
            });
            $('.dropdown-button').dropdown();
        </script>
    {% endfor %}

    <script>
        /*****  Like Functionality  ******/
        /*let likedbtn = false;
        let dislikedbtn = false; */
        
        function like()
        {
            let like = $(this);
            let type = like.data('type');
            let pk = like.data('id');
            let action = like.data('action');
            let dislike = like.next();
        
            $.ajax({
                url : "/api/" + type +"/" + pk + "/" + action + "/",
                type : 'POST',
                data : { 'obj' : pk },
        
                success : function (json) {
                    like.find("[data-count='like']").text(json.like_count);
                    dislike.find("[data-count='dislike']").text(json.dislike_count);
                }
            });
        
            return false;
        }
        
        function dislike()
        {
            let dislike = $(this);
            let type = dislike.data('type');
            let pk = dislike.data('id');
            let action = dislike.data('action');
            let like = dislike.prev();
        
            $.ajax({
                url : "/api/" + type +"/" + pk + "/" + action + "/",
                type : 'POST',
                data : { 'obj' : pk },
        
                success : function (json) {
                    dislike.find("[data-count='dislike']").text(json.dislike_count);
                    like.find("[data-count='like']").text(json.like_count);
                }
            });
        
            return false;
        }
        
        // Connecting Handlers
        $(function() {
            $('[data-action="like"]').click(like);
            $('[data-action="dislike"]').click(dislike);
        });

        /******** BookmarkFunctionality ********/

        function to_bookmarks()
        {
            var current = $(this);
            var type = current.data('type');
            var pk = current.data('id');
            var action = current.data('action');

            $.ajax({
                url : "/api/" + type + "/" + pk + "/" + action + "/",
                type : 'POST',
                data : { 'obj' : pk },

                success : function (json) {
                    current.find("[data-count='" + action + "']").text(json.count);
                }
            });

            return false;
        }

        $(function() {
            $('[data-action="bookmark"]').click(to_bookmarks);
        });
    </script>
{% endblock script %}

post/templates/post/editpost.html
{% extends "layout.html" %}

{% block title %}Edit | Bloggy{% endblock title %}

{% block head %}
    {{form.media}}
{% endblock head %}
    

{% block content %}
    <div class="container">
        <form action="{% url 'post:edit' %}" method="POST" enctype="multipart/form-data" class="create-form col s12 z-depth-5 grey white-text" style="padding-bottom:3rem;padding-top: 1rem;padding-left: 4rem;padding-right: 4rem;margin-top:4rem;color:white;">
            <h3>Edit</h3>
            {% csrf_token %}
            {% comment %} {{form.as_p}} {% endcomment %}
            <div class="input-field white-text">
                {{form.title}}
                {{form.title.label_tag}}
            </div>
            <div class="input-field white-text">
                {{form.body}}
                {{form.body.label_tag}}
            </div>
            <div class="file-field input-field white-text">
            <div class="btn black">
                <span>Thumbnail</span>
                {{form.thumbnail}}
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text" placeholder="Upload one or more files">
            </div>
            </div>
            <br>
            <input type="submit" value="Save" class="btn black">
        </form>
    </div>
{% endblock content %}
    

post/templates/post/post_delete.html
{% extends "layout.html" %}
{{form.media}}
{% block title %}Delete Post | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
        <form action="{% url 'post:post_delete' slug=post.slug %}" method="POST">
            {% csrf_token %}
            <p>Sure you want to delete "{{post}}" ?</p>
            <input type="submit" value="Confirm" class="btn red">
            <a href="{% url 'post:detail' slug=post.slug %}" class="btn black">Cancel</a>       
        </form>
    </div>
{% endblock content %}

post/templates/post/pre.html
{% extends "layout.html" %}
{{form.media}}
{% block title %}{{post.title}} | Bloggy{% endblock title %}

{% block content %}
    <div class="container">
            
        <div class="row">
            <ul id="tabs-swipe-demo" class="tabs grey" style="margin-top:6rem;">
                <li class="tab col s3"><a class="active" href="#test-swipe-1">Title</a></li>
                <li class="tab col s3"><a href="#test-swipe-2">Body</a></li>
                <li class="tab col s3"><a href="#test-swipe-3">Thumbnail</a></li>
                <li class="tab col s3"><a href="#test-swipe-4">Preview</a></li>             
            </ul>
            <!-- <div id="test-swipe-1" class="col s12"> -->
                <form action="{% url 'post:create' %}" method="POST" enctype="multipart/form-data" class="create-form col s12 z-depth-1" style="padding-bottom:3rem;padding-top: 1rem;padding-left: 4rem;padding-right: 4rem;margin-top:4rem;">
                    <!-- <h3>Create</h3> -->
                    {% csrf_token %}
                    {% comment %} {{form.as_p}} {% endcomment %}
                    <div id="test-swipe-1">
                        <h3>Title</h3>
                        <div class="input-field">
                            {{form.title}}
                            <!-- {{form.title.label_tag}} -->
                        </div>
                    </div>
                    <div id="test-swipe-2">
                        <h3>Body</h3>
                        <div class="input-field">
                            {{form.body}}
                            <!-- {{form.body.label_tag}} -->
                        </div>
                    </div>
                    <div id="test-swipe-3">
                        <h3>Thumbnail</h3>
                        <div class="file-field input-field">
                            <div class="btn black">
                                <span>Thumbnail</span>
                                {{form.thumbnail}}
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="Upload one or more files">
                            </div>
                            <input type="submit" value="Create" class="btn black">
                        </div>
                    </div>
                    <br>
                    <div id="test-swipe-4" class="col s12 preview">
                        <h3>Preview</h3>
                        <h3 class="preview-title"></h3>
                        <p class="preview-content"></p>
                    </div>
                </form>
            <!-- </div> -->
        </div>
        
    </div>
{% endblock content %}

{% block script %}
    <script>
        $('#id_title').attr('placeholder', 'Title ..');
        $('#id_body').attr('placeholder', 'Body here..');
        $(document).ready(function(){
            $('ul.tabs').tabs();

            let _title = $('#id_title');
            $('.preview-title').text(_title.val());
            _title.on('keyup', (e)=> {
                console.log(_title.val());
                $('.preview-title').text(_title.val());
            });

            let _body = $('#id_body');
            $('.preview-content').html(marked(_body.val()));
            _body.on('change', (e) => {
                console.log('changed');
                $('.preview-content').html(marked(_body.val()));
            })
            
            
        });


    </script>
{% endblock script %}